[package]
name = "sol-db"
version = "0.1.0"
authors = ["zipkr <zipkr@gmail.com>"]
edition = "2018"

[dependencies]
uuid = { version = "0.7", features = [ "u128" ] }
rand = "0.6.5"
stopwatch = "0.0.7"
